name: Release Zed Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish to zed-industries/extensions
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: salesforce
          push-to: Damecek/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
